import json,pathlib,math
p=pathlib.Path(__file__).parent;x=json.loads((p/'comparison.json').read_text());modes=['baseline','soft','package','combined'];names=x['baseline']['matrix']['classes']
def score(mode,c,l,pr):
 rs=[r for r in x[mode]['matrix']['rows'] if r['level']==l and r['aProfile']==r['bProfile']==pr and c in [r['aClass'],r['bClass']]]
 return 100*sum((r['wins']+.5*r['draws'])/r['games'] if c==r['aClass'] else 1-(r['wins']+.5*r['draws'])/r['games'] for r in rs)/len(rs)
ls=['# Soin du Moine à croissance réduite et combinaison des candidats','','## Formules et méthode','','Référence : production v0.29.1. soft : soin de 5 % des premiers 250 PV maximaux, puis 2,5 % des PV au-delà. Exemple : 200 PV → 10 soignés (inchangé) ; 300 PV → 13,75 au lieu de 15 ; 400 PV → 16,25 au lieu de 20. Il s’agit des PV maximaux après équipement. Le soin est toujours limité aux PV manquants, tous les trois tours. La règle concerne aussi la compétence copiée par Corbeau. Le seuil de 250 est une hypothèse expérimentale, pas un optimum démontré.','', 'package : Trooper ignore 15 % de défense au lieu de 25 % lors de sa compétence ; brûlure = maximum des deux sources + 25 % du minimum lors de la compétence Mage ; Chien conserve sa réduction physique et ajoute la moitié de cet effet sur la défense magique. combined : package et soft ensemble. Aucun objet retiré.','', 'Duels : neuf classes, 36 paires, niveaux 1/10/20, tous les croisements des trois profils après le niveau 1. 150 paires équipées par cellule, deux placements inversés ; même graine par paire entre variantes, mêmes équipements et raretés. 50 paires par rareté. Score : victoire 1, égalité 0,5. Répartition équilibrée = 50 % attaque/25 % endurance/25 % dextérité ; endurance = 25/50/25.','', 'Carrières : 200 par classe et variante avec statistiques équilibrées et équipement automatique ; 200 supplémentaires par variante pour Trooper équilibré, Moine endurance et Mage endurance, avec sélection intelligente des objets. Bots de production, nouvelles graines appariées entre variantes. Les mécaniques expérimentales affectent tous les combattants. Aucune attente d’énergie réelle, mais coût et règles de cœurs vérifiés par assertions.','']
for pr in ['balanced','resilient']:
 ls += [f'## Duels niveau 20 — {pr} des deux côtés','','| Classe | Actuel | Soin seul | Autres candidats | Ensemble |','|---|---:|---:|---:|---:|']
 for cs,name in names.items():ls.append('| '+name+' | '+' | '.join(f'{score(m,int(cs),20,pr):.1f} %' for m in modes)+' |')
 ls.append('')
ls+=['## Moine par niveau','','| Profil | Niveau | Actuel | Soin seul | Autres candidats | Ensemble |','|---|---:|---:|---:|---:|---:|']
for pr in ['balanced','resilient']:
 for l in [1,10,20]:ls.append(f'| {pr} | {l} | '+' | '.join(f'{score(m,7,l,"balanced" if l==1 else pr):.1f} %' for m in modes)+' |')
ls+=['','## Temple — équilibré et équipement automatique','','| Classe | Actuel | Soin seul | Autres candidats | Ensemble |','|---|---:|---:|---:|---:|']
for cs,name in names.items():ls.append('| '+name+' | '+' | '.join(f"{100*x[m]['all']['policies']['cautious']['classes'][cs]['retirementRate']:.1f} %" for m in modes)+' |')
ls+=['','## Temple avec sélection intelligente','','| Classe / profil | Actuel | Soin seul | Autres candidats | Ensemble |','|---|---:|---:|---:|---:|']
for tag in ['trooper','monk','mage']:ls.append('| '+tag+' | '+' | '.join(f"{100*x[m][tag]['policies']['cautious']['overall']['retirementRate']:.1f} %" for m in modes)+' |')
ls+=['','## Incertitude des différences appariées','']
for tag in ['trooper','monk','mage']:
 for a,b in [('baseline','combined'),('package','combined')]:
  aa=[json.loads(l) for l in (p/f'{a}-{tag}.ndjson').read_text().splitlines()];bb=[json.loads(l) for l in (p/f'{b}-{tag}.ndjson').read_text().splitlines()];assert [r['seed'] for r in aa]==[r['seed'] for r in bb]
  d=[int(v['retired'])-int(u['retired']) for u,v in zip(aa,bb)];mean=sum(d)/len(d);se=math.sqrt(sum((v-mean)**2 for v in d)/(len(d)-1)/len(d));ls.append(f'- {tag}, {a} → {b} : {mean*100:+.1f} points Temple ; IC normal approximatif 95 % [{100*(mean-1.96*se):+.1f} ; {100*(mean+1.96*se):+.1f}].')
ls+=['', 'Intervalles exploratoires sans correction pour comparaisons multiples. Les duels et les variantes partagent leurs tirages et ne sont pas indépendants. Les victoires en carrière ne sont pas des victoires à armes égales ; les adversaires sont choisis prudemment parmi les propositions. Les écarts avec les études précédentes ne sont pas des effets de traitement puisque les graines changent.','',f"Totaux : {sum(v['matrix']['totalDuels'] for v in x.values()):,} duels de matrice ; {sum(v[t]['totalCareers'] for v in x.values() for t in ['all','trooper','monk','mage']):,} carrières ; {sum(v[t]['totalPlayerMatches'] for v in x.values() for t in ['all','trooper','monk','mage']):,} combats de héros suivis, hors autres duels de pool et sélection.",'', 'Reproduction : `python balance/monk-scaling/run.py`, puis `python balance/monk-scaling/report.py`. Copies temporaires du code ; production inchangée. Les assertions existantes vérifient énergie, cœurs, limites de rencontres, terminaison, compteurs et répétabilité.','']
(p/'rapport.md').write_text('\n'.join(ls));print('\n'.join(ls[10:]))
