"""Build the report from measured results, without rerunning or changing balance."""
import json,csv,hashlib
from pathlib import Path
load=lambda name:json.loads(Path('balance/'+name+'.json').read_text())
seeds=[391027,672041,105983];runs=[load('holdout-'+str(s)) for s in seeds]
before=load('baseline-compatible');matched=load('final-matched');cb=load('campaign-before');ca=load('campaign-after');fb=load('fairy-before');fa=load('fairy-final')
d=json.loads(Path('docs/data.js').read_text().split('=',1)[1].strip().removesuffix(';'))
def pooled(bs):
 keys=['n','w','l','d','score','duration','ko'];t={k:sum(b[k] for b in bs) for k in keys}
 t.update(scorePct=t['score']/t['n']*100,drawPct=t['d']/t['n']*100,meanSeconds=t['duration']/t['n'],koPct=t['ko']/t['n']*100)
 return t
classes=[dict(id=i,name=d['CLASSES'][i],**pooled([r['classes'][i] for r in runs]),seedRange=[min(r['classes'][i]['scorePct'] for r in runs),max(r['classes'][i]['scorePct'] for r in runs)]) for i in range(13)]
items=[dict(id=i,name=d['ITEMS'][i]['name'],**pooled([r['items'][i] for r in runs]),tiers={tier:pooled([r['items'][i]['tiers'][tier] for r in runs]) for tier in ['0','2']}) for i in range(19)]
matrix=[[pooled([r['matrix'][i][j] for r in runs]) if i!=j else None for j in range(13)] for i in range(13)]
byLevel={l:[pooled([r['byLevel'][l][i] for r in runs]) for i in range(13)] for l in ['1','5','10','20']}
byPolicy={p:[pooled([r['byPolicy'][p][i] for r in runs]) for i in range(13)] for p in ['mixed','offense','defense']}
overall=pooled([r['overall'] for r in runs]);edges=[matrix[i][j]['scorePct'] for i in range(13) for j in d['ADVANTAGES'][i]]
counts={'independent':sum(r['totalDuels'] for r in runs),'matchedBeforeAfter':before['totalDuels']+matched['totalDuels'],'mixedGearBeforeAfter':cb['totalDuels']+ca['totalDuels'],'fairyStressBeforeAfter':fb['total']['n']+fa['total']['n']};count=sum(counts.values())
summary={'version':'0.6.0','date':'2026-09-07','seeds':seeds,'counts':counts,'totalDuels':count,'classes':classes,'items':items,'matrix':matrix,'byLevel':byLevel,'byPolicy':byPolicy,'overall':overall,'matchedBefore':{'classes':before['classes'],'items':[{k:v for k,v in x.items() if k!='perClass'} for x in before['items']],'overall':before['overall']},'matchedAfter':{'classes':matched['classes'],'items':[{k:v for k,v in x.items() if k!='perClass'} for x in matched['items']],'overall':matched['overall']},'mixedGearBefore':cb['classes'],'mixedGearAfter':ca['classes'],'fairyBefore':fb,'fairyAfter':fa,'sha256':{p:hashlib.sha256(Path(p).read_bytes()).hexdigest() for p in ['docs/engine.js','docs/data.js','docs/balance.js','balance/simulate.mjs','balance/fairy-stress.mjs','balance/baseline/engine.js','balance/baseline/data.js']}}
Path('balance/summary.json').write_text(json.dumps(summary,ensure_ascii=False,separators=(',',':'))+'\n')
with open('balance/matchups.csv','w') as f:
 w=csv.writer(f);w.writerow(['Classe']+d['CLASSES'])
 for i,name in enumerate(d['CLASSES']):w.writerow([name]+[round(matrix[i][j]['scorePct'],2) if i!=j else '' for j in range(13)])
lines=[]
def p(s=''):lines.append(s)
def table(headers,rows):
 p('| '+' | '.join(headers)+' |');p('| '+' | '.join(['---']*len(headers))+' |')
 for row in rows:p('| '+' | '.join(str(x) for x in row)+' |')
 p()
f=lambda n:f'{n:.1f} %';num=lambda n:f'{n:,}'.replace(',',' ')
p('# Hero Clash 0.6 — Rapport d’équilibrage');p();p('Mesures réalisées le 7 septembre 2026 avec le moteur JavaScript réellement utilisé par le jeu. Version de référence : v0.5, commit `ad4c7bfed07c78f70946f3d5673b8966949102e0`.');p()
p(f'**{num(count)} combats** dans les séries comparatives et de validation conservées, en plus des essais de réglage. La Fée était effectivement dominante. Les écarts entre classes étaient également majeurs.');p()
p('## Comment lire les chiffres');p();p('Le score est la proportion de victoires, avec un demi-point par match nul : `(victoires + 0,5 × nuls) / combats`. Une valeur de 50 % indique un équilibre moyen dans le protocole testé. Ce n’est ni une probabilité affichable pour un adversaire précis, ni une garantie pour tous les équipements. Les mêmes héros sont testés dans les deux positions ; les résultats sont donc corrélés. Les plages entre graines ci-dessous mesurent la stabilité observée, pas un intervalle de confiance statistique.');p()
table(['Série','Combats'],[['Validation indépendante : 3 graines',num(counts['independent'])],['Avant/après, fixtures et graines identiques',num(counts['matchedBeforeAfter'])],['Raretés et niveaux d’acquisition mélangés, avant/après',num(counts['mixedGearBeforeAfter'])],['Fée : combinaisons et spécialisations extrêmes, avant/après',num(counts['fairyStressBeforeAfter'])]])
p('## Classes');p();p('Les colonnes avant/après utilisent exactement les mêmes fixtures (graine 73051). La validation utilise trois nouvelles graines, jamais utilisées pour ajuster cette version finale : 391027, 672041 et 105983. Chaque classe y participe à 165 888 combats.');p()
table(['Classe','Avant, comparatif','Après, comparatif','Validation','Plage entre 3 graines'],[[c['name'],f(before['classes'][i]['scorePct']),f(matched['classes'][i]['scorePct']),f(c['scorePct']),f(c['seedRange'][0])+' – '+f(c['seedRange'][1])] for i,c in enumerate(classes)])
p('### Par niveau, validation indépendante');p();table(['Classe','Niv. 1','Niv. 5','Niv. 10','Niv. 20'],[[c['name']]+[f(byLevel[l][i]['scorePct']) for l in byLevel] for i,c in enumerate(classes)])
p('### Avantages et désavantages');p();p(f'Chaque classe possède maintenant exactement **deux avantages et deux désavantages**, sans relation réciproque ni classe favorisée par le nombre de contres. Le bonus de dégâts est de **8 %**. Les 26 affrontements favorables mesurés vont de **{f(min(edges))} à {f(max(edges))}** : un avantage compte, mais ne garantit pas la victoire.');p()
table(['Classe','Avantage contre','Désavantage contre'],[[name,', '.join(d['CLASSES'][j] for j in d['ADVANTAGES'][i]),', '.join(d['CLASSES'][j] for j in range(13) if i in d['ADVANTAGES'][j])] for i,name in enumerate(d['CLASSES'])])
p('La [matrice complète](balance/matchups.csv) contient les 156 confrontations orientées. Les cellules inverses se complètent à 100 %.');p()
p('## Équipements');p();p('Comparaisons à héros identiques : mêmes statistiques, classe et trois autres équipements, seul l’objet du slot étudié change. Chaque objet affronte un autre objet tiré uniformément dans le même slot, à niveau et rareté identiques. Pour les armes, l’épée est évaluée sur les classes physiques et le bâton sur les classes magiques ; ces restrictions concernent seulement le benchmark, toutes les armes restent autorisées en jeu. Les autres armes sont évaluées sur les 13 classes.');p()
table(['Équipement','Avant, comparatif','Après, comparatif','Validation','Commun','Rare'],[[x['name'],f(before['items'][i]['scorePct']),f(matched['items'][i]['scorePct']),f(x['scorePct']),f(x['tiers']['0']['scorePct']),f(x['tiers']['2']['scorePct'])] for i,x in enumerate(items)])
p('Les colonnes Commun et Rare comparent des objets de **même rareté**, pas un objet rare à un objet commun. Les objets ne sont pas interchangeables sur chaque build : leurs synergies restent utiles.');p()
p('### La Fée');p();p(f"Dans le comparatif standard, son score passe de **{f(before['items'][14]['scorePct'])} à {f(matched['items'][14]['scorePct'])}**. La validation indépendante donne **{f(items[14]['scorePct'])}**.");p()
p('Son soin est désormais fixe : `1,9 × (1 + 0,02 × (niveau d’acquisition − 1)) × multiplicateur de rareté` PV par tour personnel. Cela donne 1,90 PV au niveau 1 commun et 3,93 PV au niveau 20 rare. Le soin est limité aux PV manquants et ne rend jamais de cœur. L’Endurance et les armures de PV ne l’amplifient plus.');p()
p(f"Test supplémentaire : **{num(fa['total']['n'])} combats par version**, couvrant toutes les 6 armes × 4 armures × 4 objets, les 13 classes, les niveaux 1/5/10/20, les trois raretés et trois spécialisations extrêmes (tous les points en Endurance, Dextérité ou statistique offensive). Chaque combinaison affronte les quatre autres familiers dans les deux positions, avec deux graines par fixture.");p()
table(['Spécialisation','Fée avant','Fée après'],[[name,f(fb['byPolicy'][key]['scorePct']),f(fa['byPolicy'][key]['scorePct'])] for key,name in [('endurance','Tout Endurance'),('dexterity','Tout Dextérité'),('offense','Tout offensif')]]+[['Ensemble',f(fb['total']['scorePct']),f(fa['total']['scorePct'])]])
p(f"Synergie restante à surveiller : sur le Soldat médiéval, la Fée obtient **{f(fa['byClass'][4]['scorePct'])}** dans ce test de remplacement du familier, contre **{f(fb['byClass'][4]['scorePct'])}** auparavant. Ce n’est pas le taux de victoire du Soldat médiéval contre les autres classes. La Fée reste un bon choix défensif, et un choix moins intéressant sur certaines classes offensives. Je conserve cette spécialisation plutôt que d’imposer 50 % à chaque combinaison.");p()
p('## Modifications de règles et de valeurs');p();p('- Bases d’attaque propres aux classes, avec évolution linéaire du niveau 1 au niveau 20, pour conserver les statistiques et les choix de progression des héros existants. La base réelle est affichée dans la fiche de statistiques équipées. Un point offensif ajoute toujours 1,45 dégât avant multiplicateurs et défense.');p('- Rempart : bouclier de 6 % des PV maximum, contre 12 %. Paume apaisante : soin de 5 %, contre 8 %.');p('- Bonus universels de précision/vitesse retirés des raretés ; la rareté améliore désormais les effets propres aux objets. Masse : progression de rareté ×1 / ×1,075 / ×1,15, avec sa cadence −20 % conservée. Les autres bonus chiffrés utilisent ×1 / ×1,25 / ×1,5.');p('- Loup : morsure arrondie de `(4,5 + 0,3 × niveau d’acquisition) × rareté`, tous les trois tours. Chien : réduction proportionnelle de défense, puis réduction fixe de `2 × rareté`, sans défense négative.');p('- Corbeau : copie tous les quatre tours, avec bonus de précision de 6/7,5/9 % selon la rareté. Potion : 75 % de chances de bonus, 25 % de malus au début du duel ; amplitude selon niveau et rareté.');p('- Révision des valeurs de base des 19 équipements ; valeurs exactes dans `docs/data.js` et réglages dans `docs/balance.js`. Descriptions françaises/anglaises et règles mises à jour.');p('- Héros, statistiques investies, inventaires, cœurs, énergie, XP, points, adversaires mémorisés et sauvegardes restent conservés. Les objets existants utilisent les nouveaux effets.');p()
p('## Robustesse et limites');p();p(f"Le scénario à équipements mélangés (65 % communs, 28 % inhabituels, 7 % rares ; acquisition entre le niveau 1 et celui du héros ; stratégies indépendantes entre adversaires) donne une plage de classes de **{f(min(x['scorePct'] for x in ca['classes']))} à {f(max(x['scorePct'] for x in ca['classes']))}**, sur {num(ca['classDuels'])} combats.");p()
p(f"La durée moyenne du comparatif passe de **{before['overall']['meanSeconds']:.2f} s à {matched['overall']['meanSeconds']:.2f} s** ; validation : **{overall['meanSeconds']:.2f} s**, {overall['koPct']:.1f} % de KO et {overall['drawPct']:.3f} % de matchs nuls. La limite de 30 secondes reste inchangée.");p()
p('Le benchmark principal équilibre les classes et les niveaux, utilise quatre slots remplis, des raretés toutes communes ou toutes rares, des acquisitions au niveau du héros et trois stratégies d’investissement. Les armes sont favorisées à 55 % selon la classe. Le scénario mélangé apporte une autre distribution, mais ne simule pas une carrière complète avec sélection des adversaires, choix intelligent du butin et mort au cinquième échec. Les niveaux inégaux et les emplacements vides ne font pas partie des mesures d’équilibre présentées. Les tests extrêmes exhaustifs concernent les synergies de la Fée ; ils ne prouvent pas l’absence de tout combo dominant parmi tous les objets.');p()
p('Six suites automatisées passent : moteur, progression, récompenses, état des héros, nouvelles règles d’équilibre et rendu des textes FR/EN avec une ancienne sauvegarde. Les vérifications de rendu utilisent un hôte DOM minimal, pas un vrai téléphone ; aucune validation visuelle sur appareil n’est revendiquée.');p()
p('## Reproduire');p();p('Node.js et Python 3, aucune dépendance supplémentaire. Depuis la racine du dépôt :');p();p('```sh\nnode --test tests/*.test.js\npython balance/validate.py\nnode balance/fairy-stress.mjs out=balance/fairy-final.json\nnode balance/fairy-stress.mjs engine=balance/baseline/engine.js out=balance/fairy-before.json\npython balance/report.py\n```');p()
p('La [synthèse JSON](balance/summary.json) conserve les effectifs, scores, strates, matrice, graines et empreintes SHA-256 du moteur et des fixtures. Le moteur v0.5 figé est conservé dans `balance/baseline/`, hors du jeu publié. Les fichiers bruts volumineux sont régénérables par les commandes ci-dessus.');p()
Path('BALANCE_REPORT.md').write_text('\n'.join(lines))
print(json.dumps({'counts':counts,'total':count,'classRange':[min(c['scorePct'] for c in classes),max(c['scorePct'] for c in classes)],'itemRange':[min(x['scorePct'] for x in items),max(x['scorePct'] for x in items)],'fairy':items[14]['scorePct'],'edges':[min(edges),max(edges)],'duration':overall['meanSeconds'],'levelRange':[min(x['scorePct'] for a in byLevel.values() for x in a),max(x['scorePct'] for a in byLevel.values() for x in a)]}))
