import json,pathlib,math
p=pathlib.Path(__file__).parent;x=json.loads((p/'comparison.json').read_text());modes=['baseline','burn','dog','both'];names=x['baseline']['matrix']['classes']
def score(mode,c,level=20,profile='balanced'):
 rs=[r for r in x[mode]['matrix']['rows'] if r['level']==level and r['aProfile']==r['bProfile']==profile and c in [r['aClass'],r['bClass']]]
 return sum(((r['wins']+.5*r['draws'])/r['games'] if c==r['aClass'] else 1-(r['wins']+.5*r['draws'])/r['games']) for r in rs)/len(rs)*100
lines=['# Synergies brûlure et Chien — v0.29.1','','## Variantes et protocole','','baseline : production. burn : lors d’une compétence de Mage (y compris copiée par Corbeau), additionner la puissance de brûlure de l’arme et les 4 points de compétence, au lieu de prendre leur maximum. Conserver le maximum entre cette nouvelle puissance et la brûlure déjà active ; les coups suivants peuvent rafraîchir cette puissance, comme dans la logique actuelle. Il ne s’agit pas de deux effets avec des durées indépendantes.','', 'dog : conserver intégralement la réduction de défense physique du Chien et ajouter une réduction magique égale à la moitié de son effet (part proportionnelle et part fixe). Cela bénéficie aussi aux dégâts magiques secondaires des classes physiques. both : les deux variantes combinées. Aucun objet retiré.','', 'Copies temporaires des modules de production. Les modifications s’appliquent aux deux combattants et aux bots. Matrices : 36 paires de classes, niveaux 1/10/20, neuf combinaisons de profils après le niveau 1, 150 paires équipées par cellule jouées dans les deux sens. Même niveau et rareté, objets aléatoires compatibles. Graines nouvelles partagées entre variantes. Score de duel : victoire 1, nul 0,5.','', 'Carrières : 150 par classe/variante avec profil équilibré et équipement automatique ; 150 supplémentaires par variante pour le Mage endurance avec sélection intelligente d’équipement. Bots avec décisions de production ; règles de cœurs, énergie et progression inchangées. Même graine de départ par carrière entre variantes, mais trajectoires et tirages ultérieurs peuvent diverger.','', '## Duels au niveau 20 — deux profils équilibrés','','| Classe | Actuel | Brûlure | Chien | Les deux |','|---|---:|---:|---:|---:|']
for cs,name in names.items():lines.append('| '+name+' | '+' | '.join(f'{score(m,int(cs)):.1f} %' for m in modes)+' |')
lines+=['','## Temple — profils équilibrés, équipement automatique','','| Classe | Actuel | Brûlure | Chien | Les deux |','|---|---:|---:|---:|---:|']
for cs,name in names.items():lines.append('| '+name+' | '+' | '.join(f"{100*x[m]['all']['policies']['cautious']['classes'][cs]['retirementRate']:.1f} %" for m in modes)+' |')
lines+=['','## Mage endurance avec sélection d’équipement','','| Variante | Temple | Victoires en carrière |','|---|---:|---:|']
for m in modes:
 s=x[m]['mage']['policies']['cautious']['overall'];lines.append(f"| {m} | {s['retired']}/150 ({100*s['retirementRate']:.1f} %) | {100*s['winRate']:.1f} % |")
lines+=['','## Incertitude sur le Temple du Mage endurance','']
a=[json.loads(l) for l in (p/'baseline-mage.ndjson').read_text().splitlines()]
for m in modes[1:]:
 b=[json.loads(l) for l in (p/f'{m}-mage.ndjson').read_text().splitlines()];assert [r['seed'] for r in a]==[r['seed'] for r in b];d=[int(v['retired'])-int(u['retired']) for u,v in zip(a,b)];mean=sum(d)/len(d);se=math.sqrt(sum((v-mean)**2 for v in d)/(len(d)-1)/len(d));lines.append(f'- {m} : {100*mean:+.1f} points, IC normal apparié approximatif à 95 % [{100*(mean-1.96*se):+.1f} ; {100*(mean+1.96*se):+.1f}].')
lines+=['', 'Intervalles exploratoires sans correction de comparaisons multiples. Les duels et placements ne sont pas indépendants ; ne pas convertir leur nombre en certitude sur les carrières. Les taux de victoire de carrière pondèrent davantage les longs survivants.','',f"Totaux : {sum(v['matrix']['totalDuels'] for v in x.values()):,} duels de matrice, {sum(v[t]['totalCareers'] for v in x.values() for t in ['all','mage']):,} carrières, {sum(v[t]['totalPlayerMatches'] for v in x.values() for t in ['all','mage']):,} combats de héros suivis. Les duels supplémentaires de pool et de sélection d’équipement sont exclus du premier total.",'', 'Reproduction : `python balance/synergy-study/run.py`, puis `python balance/synergy-study/report.py`. Assertions du lanceur de carrière : énergie, cœurs, limite de rencontres, fin de carrière, compteurs, reproductibilité. Aucun fichier de production modifié.','']
(p/'rapport.md').write_text('\n'.join(lines));print('\n'.join(lines[12:]))
