import json,csv,pathlib
p=pathlib.Path(__file__).parent
x=json.loads((p/'results.json').read_text());names={int(k):v for k,v in x['classes'].items()};rows=x['rows'];profiles=x['profiles']
def score(r,c):
 a=(r['wins']+.5*r['draws'])/r['games']
 return 100*(a if c==r['aClass'] else 1-a)
def selected(c,l,profile='balanced',opponent='balanced'):
 return [r for r in rows if r['level']==l and ((r['aClass']==c and r['aProfile']==profile and (opponent is None or r['bProfile']==opponent)) or (r['bClass']==c and r['bProfile']==profile and (opponent is None or r['aProfile']==opponent)))]
def average(rs,c):return sum(score(r,c) for r in rs)/len(rs)
lines=['# Matrice des neuf classes — v0.29.1','','## Méthode','',f"{x['totalDuels']:,} duels : 36 paires de classes, niveaux 1, 5, 10, 15 et 20, neuf combinaisons de profils après le niveau 1. Au niveau 1, les profils sont identiques : une seule combinaison est simulée. Chaque cellule utilise 300 paires de héros, jouées dans les deux sens avec la même graine de combat. Les équipements et graines sont également partagés entre profils pour une paire et un niveau donnés.",'','Équipement aléatoire compatible dans les quatre emplacements, niveau identique entre héros et objets. Chaque paire reçoit la même rareté, avec exactement 100 tirages communs, 100 uncommon et 100 rares. Tous les familiers actuels sont conservés, dont le Chien du Mage. Pas de sélection optimisée, pas de carrière, pas de classes miroirs.','', 'Profils : offense = attaque pure ; balanced = 50 % attaque, 25 % endurance, 25 % dextérité ; resilient = 25 % attaque, 50 % endurance, 25 % dextérité. Allocation cyclique légale ; les proportions exactes dépendent du nombre de points disponibles. Attaque = Force pour les classes physiques, Intelligence pour les classes magiques.','', '**Les tableaux donnent un score de victoire : victoire = 1, égalité = 0,5, défaite = 0.** Les comptes bruts de victoires et égalités sont conservés dans results.json. Les deux placements et les profils partagent leurs tirages : ne pas les traiter comme des observations indépendantes. Les écarts de quelques points restent exploratoires, sans correction pour comparaisons multiples.','', '## Profils équilibrés des deux côtés','','| Classe | Niv. 1 | Niv. 5 | Niv. 10 | Niv. 15 | Niv. 20 |','|---|---:|---:|---:|---:|---:|']
for c in names:lines.append('| '+names[c]+' | '+' | '.join(f'{average(selected(c,l),c):.1f} %' for l in x['levels'])+' |')
lines+=['','## Sensibilité aux profils au niveau 20','','Adversaires : les huit autres classes, chacune avec ses trois profils à poids égal. Ces taux ne correspondent pas au tableau précédent, qui impose des adversaires équilibrés.','','| Classe | Attaque pure | Équilibré | Endurance |','|---|---:|---:|---:|']
for c in names:lines.append('| '+names[c]+' | '+' | '.join(f'{average(selected(c,20,pr,None),c):.1f} %' for pr in profiles)+' |')
for l in x['levels']:
 lines+=['',f'## Matrice au niveau {l} — profils équilibrés','', 'Lire chaque ligne comme le score de la classe contre la colonne.','', '| Classe | '+' | '.join(names.values())+' |','|---|'+'---:|'*len(names)]
 for c in names:
  cells=[]
  for o in names:
   if c==o:cells.append('—');continue
   r=next(r for r in selected(c,l) if o in [r['aClass'],r['bClass']]);cells.append(f'{score(r,c):.1f}')
  lines.append('| '+names[c]+' | '+' | '.join(cells)+' |')
lines+=['','## Portée','', 'Cette étude mesure la force en duels à niveau et rareté comparables. Elle ne valide pas le taux d’accès au Temple, les récompenses successives, les équipements sélectionnés intelligemment ou la difficulté des bots. Un avantage marqué contre une classe peut être cohérent avec une identité de contre ; une domination globale persistante mérite une vérification ciblée. Aucune constante du jeu n’a été modifiée.','', 'Reproduction : `node balance/matrix-audit/run.mjs`, puis `python balance/matrix-audit/report.py`. Sources locales : docs/engine.js, docs/data.js et docs/balance.js de la v0.29.1 ; allocation réutilisée depuis balance/decision-audit/decisions.mjs.','']
lines+=['## Diagnostic et suite recommandée','', 'Avec les deux profils équilibrés, le Trooper atteint 56,7 % au niveau 20 et le Guerrier 54,2 %, contre 44,2 % pour le Mage. Le Ninja (49,5 %) et le Berserker (51,6 %) ne présentent pas de faiblesse globale dans ce cadre. Le classement diffère des carrières : le Paladin y était très performant, mais termine ici à 49,0 %.','', 'Au niveau 20, certains affrontements dépassent 65/35 : Trooper contre Moine 70,8 %, Guerrier contre Archer 70,3 %, Archer contre Mage 69,5 %, Paladin contre Ingénieur 69,5 %. Ces écarts ne sont pas à corriger automatiquement : les avantages de classe et les pools différents font partie du modèle. Il reste à mesurer leur impact dans les choix proposés en carrière.','', 'La sensibilité aux statistiques est majeure : contre un mélange égal des trois profils adverses, le Mage passe de 30,4 % en attaque pure à 57,5 % en endurance. Le Moine endurance atteint 58,8 %. Cela suggère de vérifier les compromis entre attaque et survie avant de modifier les dégâts propres aux classes. Ce sont des moyennes contre une population de profils imposée, pas un équilibre stratégique où chaque classe choisit son meilleur profil.','', 'Prochaine vérification : isoler les armes, armures et familiers du Trooper et du Mage par remplacements contrôlés, conserver le Chien, puis tester les candidats en carrière sur les neuf classes. Confirmer tout ajustement sur de nouvelles graines. Aucun bonus ou nerf recommandé pour déploiement sur la seule base de cette matrice.','']
(p/'rapport.md').write_text('\n'.join(lines))
with (p/'matchups.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['level','class_a','class_b','profile_a','profile_b','games','wins_a','draws','score_a_percent'])
 for r in rows:w.writerow([r['level'],names[r['aClass']],names[r['bClass']],r['aProfile'],r['bProfile'],r['games'],r['wins'],r['draws'],round(score(r,r['aClass']),3)])
print('\n'.join(lines[12:40]))
